# Generated by Django 4.2.6 on 2023-10-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceperson',
            name='insured_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='insured_person/'),
        ),
        migrations.AddField(
            model_name='insuredfamilymember',
            name='insured_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='insured_family_member/'),
        ),
    ]
