# Generated by Django 4.2.6 on 2023-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_insuranceperson_insured_person_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceperson',
            name='date_of_insurance',
            field=models.DateField(default='2023-10-20'),
        ),
    ]
