# Generated by Django 4.2.6 on 2023-10-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_insuranceperson_date_of_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuredfamilymember',
            old_name='insured_person_image',
            new_name='family_member_image',
        ),
    ]
