# Generated by Django 4.2.6 on 2023-10-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_insured_person_image_insuredfamilymember_family_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceperson',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='insuranceperson',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='insuranceperson',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='insuredfamilymember',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='insuredfamilymember',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
