# Generated by Django 4.2.6 on 2023-10-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_insuranceperson_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredfamilymember',
            name='insurance_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='apps.insuranceperson'),
        ),
    ]
