# Generated by Django 4.2.6 on 2023-10-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_insuredfamilymember_insurance_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredfamilymember',
            name='insurance_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_family_members', to='apps.insuranceperson'),
        ),
    ]
